/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Triplos;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Geovani Alberto tuz Poot
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        txtInfija = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInfija.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInfija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                txtInfijaActionPerformed(evt);
            }
        });

        btnGenerar.setText("GenerarCodigo");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Intermedio");

        jLabel3.setText("Lenguaje y automastas II");

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(134, 134, 134).addComponent(btnGenerar))
                                .addGroup(layout.createSequentialGroup().addGap(120, 120, 120).addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel3)))
                        .addContainerGap(147, Short.MAX_VALUE))
                .addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(40, 40, 40)
                                        .addComponent(txtInfija, javax.swing.GroupLayout.PREFERRED_SIZE, 316,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(44, Short.MAX_VALUE))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel3).addGap(27, 27, 27)
                        .addComponent(jLabel2).addGap(65, 65, 65)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(56, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(89, 89, 89)
                                .addComponent(txtInfija, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(100, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>

    private void txtInfijaActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtInfijaActionPerformed
        // TODO add your handling code here: xfg
    }// GEN-LAST:event_txtInfijaActionPerformed

    private void btnGenerarActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGenerarActionPerformed

        try {

            final String infija = this.txtInfija.getText().trim();
            String infijaPura = "";
            final Evaluador codigo = new Evaluador();

            for (int i = 0; i < infija.length(); i++) {
                if (infija.charAt(i) != ' ') {
                    infijaPura += infija.charAt(i);
                    System.out.println(infijaPura);
                }
            }
            System.out.println("con valor "+infijaPura);
            final ArrayList a = codigo.temporales(infijaPura);

            for (int i = 0; i < a.size(); i++) {

                JOptionPane.showMessageDialog(this, a.get(i));
                System.out.println(i);
                System.out.println(a);
            }
            a.removeAll(a);
        } catch (final Exception e) {
            JOptionPane.showMessageDialog(null, " Campo vacio o argumentos no validos");

            this.txtInfija.setText(null);
        }

    }// GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (final ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (final javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGenerar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtInfija;
    // End of variables declaration//GEN-END:variables
}
